declare const styles: {
    contactList: string;
    container: string;
    row: string;
    column: string;
    'ms-Grid': string;
    title: string;
    subTitle: string;
    description: string;
    button: string;
    label: string;
    parentContainer: string;
    contactName: string;
    contactTitle: string;
    contactValue: string;
    contact: string;
    contactContainer: string;
    formContainer: string;
    padDiv: string;
    padDivSmall: string;
    styleMargin: string;
};
export default styles;
